name: Linter

on: push

jobs:
  lint:
   name: Lint code
   runs-on: ubuntu-latest
   steps:
    -name: Checkout
     uses: actions/checkout@v2
     
    -name: Run Linter
     uses: github/super-linter@v3
     
     env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
